---

# Static Menu in the header.
# header_static:
#   - name: Blog
#     pageRef: /blog
#     weight: 10
#   - name: About
#     pageRef: /about
#     weight: 20

# Social links will be shown in the footer and/or header.
# Links will display icons if the icon is set.
social:
  - name: GitHub
    url: https://github.com/flokoe/hugo-neodoc
    weight: 10
    params:
      icon: github
  - name: BlueSky
    url: https://bsky.app/profile/flokoe.de
    weight: 20
    params:
      icon: bluesky
